# Generated by Django 5.2.3 on 2025-06-26 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nome completo')),
                ('register_number', models.CharField(max_length=18, unique=True, verbose_name='CPF/CNPJ')),
                ('email', models.EmailField(max_length=50, unique=True, verbose_name='E-mail')),
                ('password', models.CharField(max_length=100, verbose_name='Senha')),
            ],
        ),
    ]
