# Generated by Django 5.2.3 on 2025-06-26 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=30, unique=True, verbose_name='Número da conta')),
                ('bank', models.CharField(max_length=50, verbose_name='Banco')),
                ('agency', models.CharField(max_length=30, verbose_name='Agência')),
                ('account_type', models.CharField(choices=[('Conta corrente', 'CC'), ('Conta Poupança', 'CP'), ('Conta Salário', 'CS'), ('Conta Conjunta', 'CCJ')], verbose_name='Tipo de conta')),
                ('balance', models.FloatField(verbose_name='Saldo')),
                ('client_id', models.ForeignKey(max_length=120, on_delete=django.db.models.deletion.PROTECT, related_name='client_account', to='clients.client', verbose_name='Cliente')),
            ],
        ),
    ]
