# Generated by Django 5.2.3 on 2025-06-29 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('CC', 'Conta corrente'), ('CP', 'Conta Poupança'), ('CS', 'Conta Salário'), ('CCJ', 'Conta Conjunta')], verbose_name='Tipo de conta'),
        ),
    ]
