# Generated by Django 5.2.3 on 2025-06-26 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cash', models.FloatField(verbose_name='Valor')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Data')),
                ('destination_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions_received', to='accounts.account', verbose_name='Conta de destino')),
                ('origin_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions_sent', to='accounts.account', verbose_name='Conta de origem')),
            ],
        ),
    ]
